#Configuration de Sonata UserBundle


sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /edit


sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin


#sonata_user_security:
#    resource: "@ApplicationSonataUserBundle/Resources/config/routing/sonata_security_1.xml"
#
#sonata_user_resetting:
#    resource: "@ApplicationSonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
#    prefix: /resetting
#
#sonata_user_profile:
#    resource: "@ApplicationSonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
#    prefix: /profile
#
#sonata_user_change_password:
#    resource: "@ApplicationSonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
#    prefix: /profile
#
#sonata_user_register:
#    resource: "@ApplicationSonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
#    prefix: /register
#
#sonata_user_change_password:
#    resource: "@ApplicationSonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
#    prefix: /edit
#
#
#sonata_user:
#    resource: '@ApplicationSonataUserBundle/Resources/config/routing/admin_security.xml'
#    prefix: /admin

