periodefacture_informations:
    path:     /periodefacture/{idContrat}
    defaults: { _controller: JanetTransitAdminBundle:PeriodeFacture:index }

periodefacture_create:
    path:     /periodefacturecreate/create
    defaults: { _controller: JanetTransitAdminBundle:PeriodeFacture:create }

periodefacture_edit:
    path:     /periodefacture/{id}/{idContrat}
    defaults: { _controller: JanetTransitAdminBundle:PeriodeFacture:edit }

periodefacture_update:
    path:     /periodefacture/{id}/
    defaults: { _controller: JanetTransitAdminBundle:PeriodeFacture:update }

periodefacture_checkDate:
    path:     /periodefacturecheckDate/{idEmploye}
    defaults: { _controller: JanetTransitAdminBundle:PeriodeFacture:checkDate, _locale : fr}
    options:
        expose: true

periodefacture_delete:
    path:     /periodefacturedel/delete/{id}/{del}/{idRefresh}
    defaults: { _controller: JanetTransitAdminBundle:PeriodeFacture:delete, _locale : fr}
    options:
        expose: true