imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    #SONATA ADMIN BUNDLE
    - { resource: sonata/config/admin.yml }
    #SONATA MEDIA BUNDLE
    - { resource: sonata/config/media.yml }
    #SONATA FORMATTER BUNDLE
#    - { resource: sonata/config/formatter.yml }
     #SONATA USER BUNDLE
    - { resource: sonata/config/user.yml }
    #VICH UPLOADEE BUNDLE
    - { resource: vichUploader/config/vich.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    #sonata.user.form.type.security_roles.class: Sonata\UserBundle\Form\Type\SecurityRolesType
    #sonata.user.profile.form.type.class:  Sonata\UserBundle\Form\Type\ProfileType
    #sonata.user.profile.form.handler.default.class: Sonata\UserBundle\Form\Handler\ProfileFormHandler

    #sonata.user.admin.user.class:              Sonata\UserBundle\Admin\Entity\UserAdmin
    #sonata.user.admin.user.controller:         SonataAdminBundle:CRUD
    #sonata.user.admin.user.translation_domain: SonataUserBundle

    #sonata.user.admin.group.class:              Sonata\UserBundle\Admin\Entity\GroupAdmin
    #sonata.user.admin.group.controller:         SonataAdminBundle:CRUD
    #sonata.user.admin.group.translation_domain: %sonata.user.admin.user.translation_domain%

    #sonata.user.admin.groupname: sonata_user

#    classe de nouvelle configuration des fields
#    sonata.user.admin.user.class: JanetTransit\AdminBundle\Admin\UserAdmin

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
#    translator:     ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form :
        resources:
            - 'SonataMediaBundle:Form:media_widgets.html.twig'
#            - 'SonataFormatterBundle:Form:formatter.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        #naming_strategy: doctrine.orm.naming_strategy.underscore
        #auto_mapping: true
        entity_managers:
            default:
                mappings:
                    JanetTransitWikiBundle: ~
                    JanetTransitAdminBundle: ~
                    SonataMediaBundle: ~
                    ApplicationSonataMediaBundle: ~
                    FOSUserBundle:     ~
                    SonataUserBundle: ~
                    ApplicationSonataUserBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


