# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    role_hierarchy:
            ROLE_USER:
            ROLE_SECRETAIRE:  [ROLE_USER, ROLE_BUREAU]
            ROLE_GESTION:     [ROLE_USER]
            ROLE_MANAGER:     [ROLE_GESTION, ROLE_CARBURATION, ROLE_SECRETAIRE]
            ROLE_ADMIN:       [ROLE_MANAGER, ROLE_SONATA_ADMIN, ROLE_MODERATOR]
            ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
            SONATA:
                - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT
                - ROLE_ADMIN

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    acl:
        connection: default
    providers:
        fos_userbundle:
            id: fos_user.user_manager
        #in_memory:
         #   memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
            logout:
                path:           /admin/logout
            anonymous:          true

        main:
            #anonymous: ~
            pattern:  .*
            context:             user
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                # redirection après login
                default_target_path: /
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
            logout:
                path:        /logout
                target:      /
#                target:      /fr
#            logout:             true
                #sonata pageBundle config
                #handlers: ['sonata.page.cms_manager_selector']
            anonymous:          true

    access_control:
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Admin login page needs to be access without credential
        - { path: ^/admin/login$, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/admin/logout$, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/admin/login_check$, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/contratets/.*, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }

        # Restriction des pages de l'application Accès Sécrétaire
        - { path: ^/contrat/.*, role: ROLE_SECRETAIRE }
        - { path: ^/fichedepaie/.*, role: ROLE_SECRETAIRE }
        - { path: ^/avancesalaire/.*, role: ROLE_SECRETAIRE }
        - { path: ^/presence/.*, role: ROLE_SECRETAIRE }
        - { path: ^/demandepermission/.*, role: ROLE_SECRETAIRE }
        - { path: ^/sanction/.*, role: ROLE_SECRETAIRE }
        - { path: ^/reunion/.*, role: ROLE_SECRETAIRE }
        - { path: ^/carburation/.*, role: ROLE_SECRETAIRE }
        - { path: ^/periodecarburation/.*, role: ROLE_SECRETAIRE }
        - { path: ^/facture/.*, role: ROLE_SECRETAIRE }
        - { path: ^/periodefacture/.*, role: ROLE_SECRETAIRE }
        - { path: ^/depense/.*, role: ROLE_SECRETAIRE }
        - { path: ^/periodedepense/.*, role: ROLE_SECRETAIRE }

        # Restriction des pages de l'application Accès Gestionnaire
        - { path: ^/stock/.*, role: ROLE_GESTION }
        - { path: ^/periodestock/.*, role: ROLE_GESTION }
        - { path: ^/typevoiture, role: ROLE_GESTION }
        - { path: ^/voitureinfos/.*, role: ROLE_GESTION }
        - { path: ^/document/.*, role: ROLE_GESTION }

        # Restriction des pages de l'application Accès Manager
        - { path: ^/poste/.*, role: ROLE_MANAGER }
        - { path: ^/service/.*, role: ROLE_MANAGER }
        - { path: ^/taf, role: ROLE_MANAGER }
        - { path: ^/taches/.*, role: ROLE_MANAGER }
        - { path: ^/suivi/.*, role: ROLE_MANAGER }
        - { path: ^/prime/.*, role: ROLE_MANAGER }


        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/profile/edit-profile, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/_console, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: ROLE_USER }
#        - { path: ^/profile$, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }

