<?php

namespace JanetTransit\AdminBundle\Entity\Repository;

/**
 * CarburationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarburationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPeriodeBuilder($periode){

        $qb =  $this->createQueryBuilder('f')
            ->leftJoin('f.periodeCarburation', 'p')
            ->addSelect('p')
            ->where('p.dateCarburation LIKE :periode AND f.del = 0')
            ->setParameter('periode', '%'.$periode.'%')
        ;
        return $qb->getQuery()->getResult();
    }

    public function findByCarburationValidBuilder($periode, $validation){

        $qb =  $this->createQueryBuilder('f')
            ->leftJoin('f.periodeCarburation', 'p')
            ->addSelect('p')
            ->where('p.dateCarburation LIKE :periode AND f.valid =:validation AND f.del = 0 ')
            ->setParameters(array('periode' => '%'.$periode.'%', 'validation' => $validation))
        ;
        return $qb->getQuery()->getResult();
    }
}
