<?php

namespace JanetTransit\AdminBundle\Entity\Repository;

/**
 * DepenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepenseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPeriodeBuilder($periode){

        $qb =  $this->createQueryBuilder('d')
            ->leftJoin('d.periodeDepense', 'p')
            ->addSelect('p')
            ->where('p.dateDepense LIKE :periode AND d.del = 0')
            ->setParameter('periode', '%'.$periode.'%')
        ;
        return $qb->getQuery()->getResult();
    }

    public function findByDepenseValidBuilder($periode, $validation){

        $qb =  $this->createQueryBuilder('d')
            ->leftJoin('d.periodeDepense', 'p')
            ->addSelect('p')
            ->where('p.dateDepense LIKE :periode AND d.valid =:validation AND d.del = 0 ')
            ->setParameters(array('periode' => '%'.$periode.'%', 'validation' => $validation))
        ;
        return $qb->getQuery()->getResult();
    }

    public function findByDepenseByTypeBuilder($periode, $type){

        $qb =  $this->createQueryBuilder('d')
            ->leftJoin('d.periodeDepense', 'p')
            ->addSelect('p')
            ->leftJoin('p.typeDepense', 't')
            ->addSelect('t')
            ->where('p.dateDepense LIKE :periode AND t.nom LIKE :type AND d.del = 0 ')
            ->setParameters(array('periode' => '%'.$periode.'%', 'type' => $type))
        ;

        $result = $qb->getQuery()->getResult();
        $total  = 0;

        foreach($result as $data){
            $total += $data->getMontant();
        }
        return $total;
    }
}
