<?php

namespace JanetTransit\AdminBundle\Entity\Repository;

/**
 * EmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array Ces deux fonctions vont de paires findActiveService et findActiveServiceQueryBuilder
     * @return List of Employe By Poste Chauffeur
     */

    public function findChauffeurQueryBuilder(){

        $qb =  $this->createQueryBuilder('e')
                    ->leftJoin('e.poste', 'p')
                    ->addSelect('p')
                    ->where('p.nom LIKE :chauffeur AND e.del = 0')
                    ->setParameter('chauffeur', '%chauffeur%')
        ;
        return $qb;
    }

    public function findMotoboyQueryBuilder(){

        $qb =  $this->createQueryBuilder('e')
            ->leftJoin('e.poste', 'p')
            ->addSelect('p')
            ->where('p.nom LIKE :motoboy AND e.del = 0')
            ->setParameter('motoboy', '%motoboy%')
        ;
        return $qb;
    }
}
