<?php

namespace JanetTransit\AdminBundle\Entity\Repository;

/**
 * FactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPeriodeBuilder($periode){

        $qb =  $this->createQueryBuilder('f')
            ->leftJoin('f.periodeFacture', 'p')
            ->addSelect('p')
            ->where('p.dateFacture LIKE :periode AND f.del = 0 AND f.valid = 0')
            ->setParameter('periode', '%'.$periode.'%')
        ;
        return $qb->getQuery()->getResult();
    }

    public function findByMouvementEffectueBuilder($periode, $validation){

        $qb =  $this->createQueryBuilder('f')
            ->leftJoin('f.periodeFacture', 'p')
            ->addSelect('p')
            ->where('p.dateFacture LIKE :periode AND f.valid =:validation AND f.del = 0 ')
            ->setParameters(array('periode' => '%'.$periode.'%', 'validation' => $validation))
        ;
        return count($qb->getQuery()->getArrayResult());
    }
}
