<?php

namespace JanetTransit\AdminBundle\Entity\Repository;

/**
 * PeriodeDepenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodeDepenseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTypeDepenseAndContratQueryBuilder($idTypeDepense, $idContrat){

        $qb =  $this->createQueryBuilder('d')
            ->join('d.typeDepense', 't')
            ->addSelect('t')
            ->join('d.contrat', 'c')
            ->addSelect('c')
            ->where('t.id =:idTypeDepense AND c.id =:idTypeDepense')
            ->setParameter('idTypeDepense', $idTypeDepense)
//            ->setParameter('idContrat', $idContrat)
        ;
        return $qb->getQuery()->getResult();
    }
}
