<?php

namespace JanetTransit\AdminBundle\Entity\Repository;

/**
 * SanctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SanctionRepository extends \Doctrine\ORM\EntityRepository
{
}
