<?php

namespace JanetTransit\AdminBundle\Entity\Repository;

/**
 * TacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TacheRepository extends \Doctrine\ORM\EntityRepository
{
    function findByIdEmploye($idEmploye){

        $query = $this->createQueryBuilder('t');
        $query->join('t.employe', 'e')
              ->addSelect('e');

        $query->where($query->expr()->in('e.id', $idEmploye));

        $results = $query->getQuery()->getResult();

        return $results;
    }


}
