<?php

namespace JanetTransit\AdminBundle\Entity\Repository;

/**
 * TafRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TafRepository extends \Doctrine\ORM\EntityRepository
{
}
