<?php

namespace JanetTransit\AdminBundle\Entity\Repository;

/**
 * TypeDepenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDepenseRepository extends \Doctrine\ORM\EntityRepository
{
}
